---
latitude: '52.070375'
longitude: "-9.574189"
map_zoom: 12
name: Demo Hotel
email: support@traveltripper.com
phone_number: 123-123-1234
address:
  street1: Lexington Ave
  state: NY
  city: New York
  zip_code: 
default_currency: USD
default_timezone: America/New_York
_hotel_id: HODE
_portal_id: demo
_root_path: https://rt3api-prd.ttaws.com
_ttweb_plugins_version: v3.2.2
__EDITABLE_FIELDS__:
  name:
    required: true
  logo:
    type: image
  email:
    type: string
  phone:
    type: string
  default_currency:
    required: true
  address:
    type: complex
    fields:
      street1:
        type: string
      state:
        type: string
      city:
        type: string
      zip_code:
        type: string
  map_zoom:
    type: integer
    latitude:
      type: float
    longitude:
      type: float
logo:
  name: Logo WhiteMosaic@2x
  content_type: image/png
  date_added: 2019-03-07-103713
  url_thumb: "//res.cloudinary.com/traveltripperweb/image/upload/c_fill,g_faces,h_140,w_140/v1551973033/mdqklsrfuatzn3guxbec.png"
  url_xsmall: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_300,w_300/v1551973033/mdqklsrfuatzn3guxbec.png"
  url_small: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_768,w_768/v1551973033/mdqklsrfuatzn3guxbec.png"
  url_medium: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_992,w_992/v1551973033/mdqklsrfuatzn3guxbec.png"
  url_large: "//res.cloudinary.com/traveltripperweb/image/upload/c_fit,h_1200,w_1200/v1551973033/mdqklsrfuatzn3guxbec.png"
  url_xlarge: "//res.cloudinary.com/traveltripperweb/image/upload/c_limit,h_1920,w_1920/v1551973033/mdqklsrfuatzn3guxbec.png"
  width: 316
  height: 228
  format: png
  url: "//res.cloudinary.com/traveltripperweb/image/upload/v1551973033/mdqklsrfuatzn3guxbec.png"
  resource_type: image
  size: 18372
  path: "//res.cloudinary.com/traveltripperweb/image/upload/v1551973033/mdqklsrfuatzn3guxbec.png"
  file_size: 
  alt: Logo WhiteMosaic@2x
